# GitHub Actions Workflow: Claude Code Review
# This example shows how to use Claude CLI for automated code reviews in pull requests

name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # Allows manual triggering

jobs:
  code_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for Git operations

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Claude CLI
        run: npm install -g @anthropic-ai/claude-code

      - name: Run Claude Code Review
        id: claude_review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Get diff for the current PR
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            DIFF_CONTENT=$(git diff origin/${{ github.base_ref }}...HEAD)
          else
            DIFF_CONTENT=$(git diff HEAD~1 HEAD)
          fi

          if [ -z "$DIFF_CONTENT" ]; then
            echo "No changes to review."
            echo "review_output=No changes to review." >> $GITHUB_OUTPUT
            echo "has_review=false" >> $GITHUB_OUTPUT
          else
            echo "$DIFF_CONTENT" | \
              claude -p "Review these code changes for potential bugs, security vulnerabilities, and adherence to best practices. Provide actionable suggestions for improvement. Format your response as a markdown list." \
              --output-format json \
              --no-interactive \
              --allowedTools "Read,Grep" \
              --model claude-sonnet-4.5 \
              > claude_review_output.json || {
                echo "Claude review failed." > claude_review_output.json
                echo '{"result":"Review failed"}' > claude_review_output.json
              }
            
            REVIEW_OUTPUT=$(cat claude_review_output.json | jq -r '.result // "Review completed"')
            COST=$(cat claude_review_output.json | jq -r '.total_cost_usd // "N/A"')
            
            echo "review_output<<EOF" >> $GITHUB_OUTPUT
            echo "$REVIEW_OUTPUT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "cost=$COST" >> $GITHUB_OUTPUT
            echo "has_review=true" >> $GITHUB_OUTPUT
          fi

      - name: Post Review Comment on PR
        if: github.event_name == 'pull_request' && steps.claude_review.outputs.has_review == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const reviewOutput = `${{ steps.claude_review.outputs.review_output }}`;
            const cost = `${{ steps.claude_review.outputs.cost }}`;
            const prNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            if (reviewOutput && reviewOutput.trim() !== '' && reviewOutput !== 'Review failed') {
              const body = `## 🤖 Automated Code Review by Claude\n\n${reviewOutput}\n\n---\n*Generated by Claude CLI in CI/CD* | Cost: ${cost} USD`;
              
              await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: owner,
                repo: repo,
                body: body
              });
            } else {
              console.log('No review output to post or review failed.');
            }

      - name: Upload Review Output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: claude-review-${{ github.run_id }}
          path: claude_review_output.json
          retention-days: 7
