# GitHub Actions Workflow: Cline Code Review
# This example shows how to use Cline CLI for automated code reviews in pull requests

name: Cline Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # Allows manual triggering

jobs:
  cline-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for Git operations

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cline CLI
        run: npm install -g cline

      - name: Authenticate Cline
        env:
          CLINE_API_KEY: ${{ secrets.CLINE_API_KEY }}
        run: |
          echo "Authenticating Cline CLI..."
          # Non-interactive auth for CI/CD
          cline auth --non-interactive || echo "Auth may require manual setup"

      - name: Initialize Cline instance
        run: cline instance new --default

      - name: Run Cline Code Review
        id: cline_review
        run: |
          cline review --output=review.md || {
            echo "Review failed" > review.md
            exit 1
          }

      - name: Post Review Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let review = 'Code review completed.';
            try {
              review = fs.readFileSync('review.md', 'utf8');
            } catch (e) {
              console.log('Review file not found, using default message');
            }
            
            if (review && review.trim() !== '' && review !== 'Review failed') {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🤖 Cline Code Review\n\n${review}\n\n---\n*Generated by Cline CLI in CI/CD*`
              });
            } else {
              console.log('No review output to post or review failed.');
            }

      - name: Upload Review Output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cline-review-${{ github.run_id }}
          path: review.md
          retention-days: 7

