# GitHub Actions Workflow: GitHub Copilot Code Review
# This example shows how to use GitHub Copilot CLI for automated code reviews
# Note: Requires GitHub Copilot access and authentication

name: Copilot Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Copilot CLI
        run: npm install -g @github/copilot

      - name: Authenticate with GitHub Copilot
        # Note: Copilot CLI uses GitHub authentication
        # You may need to configure authentication via GitHub token or Copilot access
        run: |
          echo "GitHub Copilot CLI authentication required"
          echo "Ensure your GitHub account has Copilot access"
          copilot --version || echo "Authentication may be required"

      - name: Run Code Review
        id: review
        env:
          # Set COPILOT_ALLOW_ALL for non-interactive mode
          COPILOT_ALLOW_ALL: 1
        run: |
          git diff origin/${{ github.base_ref }}...HEAD | \
            copilot -p "Review these changes for bugs, security issues, and code quality. Provide specific suggestions." \
            --model claude-sonnet-4.5 \
            --no-color \
            --silent \
            --allow-all-tools \
            > review.txt || echo "Review failed" > review.txt

      - name: Parse Review Results
        id: parse_review
        run: |
          if [ -f review.txt ]; then
            REVIEW_TEXT=$(cat review.txt)
            echo "review_text<<EOF" >> $GITHUB_OUTPUT
            echo "$REVIEW_TEXT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "review_text=Review file not found" >> $GITHUB_OUTPUT
          fi

      - name: Post Review Comment
        uses: actions/github-script@v7
        with:
          script: |
            const reviewText = `${{ steps.parse_review.outputs.review_text }}`;
            
            const body = `## 🤖 AI Code Review (GitHub Copilot)\n\n${reviewText}\n\n---\n*Generated by GitHub Copilot CLI*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Upload Review Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: copilot-review
          path: review.txt
          retention-days: 7

