# GitHub Actions Workflow: Codex Autofix CI
# This example shows how to use Codex to automatically fix CI failures
# Based on: https://developers.openai.com/codex/guides/autofix-ci/
# Note: Requires OpenAI API key and proper permissions

name: Codex Autofix CI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  autofix:
    # Only run if the CI workflow failed
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Codex Autofix
        id: run_codex
        uses: openai/codex-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt: |
            The CI workflow failed. Please:
            1. Diagnose the CI failures
            2. Create a minimal patch that fixes the issues
            3. Ensure the fix doesn't break existing functionality
          sandbox: workspace-write
          safety-strategy: drop-sudo
          codex-args: '["--full-auto", "--json", "--color", "never"]'
          output-file: codex-autofix-output.md

      - name: Check if fixes were applied
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request with Fixes
        if: steps.check_changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Autofix: Address CI failures (Codex)"
          title: "🤖 Autofix: CI Failures"
          body: |
            This PR contains automated fixes generated by Codex to address CI failures.
            
            ## Changes
            - Diagnosed CI failures
            - Applied minimal patches to fix issues
            - Verified fixes don't break existing functionality
            
            ## Codex Output
            See the workflow logs for detailed Codex output.
            
            Please review the changes before merging.
          branch: codex-autofix/${{ github.run_id }}
          delete-branch: true

      - name: Upload Codex Output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codex-autofix-${{ github.run_id }}
          path: codex-autofix-output.md
          retention-days: 7

      - name: Post Summary Comment
        if: steps.check_changes.outputs.changes_detected == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let comment = '## 🤖 Codex Autofix Applied\n\n';
            
            if (fs.existsSync('codex-autofix-output.md')) {
              const content = fs.readFileSync('codex-autofix-output.md', 'utf8');
              comment += '### Fixes Applied\n\n' + content.substring(0, 1000) + '\n\n';
            }
            
            comment += 'A pull request has been created with the fixes. Please review before merging.';
            
            // Try to find the associated issue or PR
            const workflowRun = context.payload.workflow_run;
            if (workflowRun && workflowRun.pull_requests && workflowRun.pull_requests.length > 0) {
              const pr = workflowRun.pull_requests[0];
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: comment
              });
            }
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

