# GitHub Actions Workflow: Factory AI Droid Code Review
# This example shows how to use Factory AI Droid CLI for automated code reviews in pull requests

name: Factory AI Droid Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # Allows manual triggering

jobs:
  code_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for Git operations

      - name: Install Factory CLI
        run: |
          curl -fsSL https://app.factory.ai/cli | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify Factory CLI installation
        run: |
          droid --version || echo "Factory CLI version check failed"

      - name: Run Droid Code Review
        id: droid_review
        env:
          FACTORY_API_KEY: ${{ secrets.FACTORY_API_KEY }}
        run: |
          # Get diff for the current PR
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            DIFF_CONTENT=$(git diff origin/${{ github.base_ref }}...HEAD)
          else
            DIFF_CONTENT=$(git diff HEAD~1 HEAD)
          fi

          if [ -z "$DIFF_CONTENT" ]; then
            echo "No changes to review."
            echo "review_output=No changes to review." >> $GITHUB_OUTPUT
            echo "has_review=false" >> $GITHUB_OUTPUT
          else
            # Run in read-only mode (safest for CI/CD)
            echo "$DIFF_CONTENT" | \
              droid exec --output-format json \
              --model sonnet \
              "Review these code changes for potential bugs, security vulnerabilities, and adherence to best practices. Provide actionable suggestions for improvement. Format your response as a markdown list." \
              > droid_review_output.json 2>&1 || {
                echo "Droid review failed." > droid_review_output.json
                echo '{"result":"Review failed"}' >> droid_review_output.json
              }
            
            # Extract review from JSON output
            if command -v jq &> /dev/null; then
              REVIEW_OUTPUT=$(cat droid_review_output.json | jq -r '.result // "Review completed"' 2>/dev/null || echo "Review completed")
            else
              REVIEW_OUTPUT=$(cat droid_review_output.json | grep -o '"result":"[^"]*"' | cut -d'"' -f4 || echo "Review completed")
            fi
            
            echo "review_output<<EOF" >> $GITHUB_OUTPUT
            echo "$REVIEW_OUTPUT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "has_review=true" >> $GITHUB_OUTPUT
          fi

      - name: Post Review Comment on PR
        if: github.event_name == 'pull_request' && steps.droid_review.outputs.has_review == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const reviewOutput = `${{ steps.droid_review.outputs.review_output }}`;
            const prNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            if (reviewOutput && reviewOutput.trim() !== '' && reviewOutput !== 'Review failed') {
              await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: owner,
                repo: repo,
                body: `## 🤖 Automated Code Review by Factory AI Droid\n\n${reviewOutput}\n\n---\n*Generated by Factory AI Droid CLI in CI/CD*`
              });
            } else {
              console.log('No review output to post or review failed.');
            }

      - name: Upload Review Output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: droid-review-${{ github.run_id }}
          path: droid_review_output.json
          retention-days: 7

